# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HumanGeo Data Blog
email: mla@thehumangeo.com
description: > # this means to ignore newlines until "baseurl:"
  The HumanGeo Data blog is focused on highlighting interesting Data Science
  and Engineering problems. We appreciate feedback and would like to hear from
  you. If these problems interest you and you are looking for a job, let us know
  because we are hiring.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://humangeo.github.io" # the base hostname & protocol for your site
twitter_username: thehumangeo
github_username:  humangeo

# Build settings
markdown: kramdown
